### ISSUE TITLE
Bane Fiend's Grip Issues

### ISSUE THREAD

**Issue by fcalife** [Pizzalol/SpellLibrary#10]
1. Mana drain should be a % of the target's max mana (currently a fixed value);
2. Mana drain should also give the same mana removed from the target to Bane (currently just removing mana from the target);
3. Bane should receive the MODIFIER_STATE_LOW_ATTACK_PRIORITY state during FIend's Grip channeling (related to the Aghs upgrade, but still);
4. Should check for invisibility upon cast, then provide true sight on the target if invisibility is detected.

**Comment by Pizzalol** [comment]
Thanks for the detailed report!

**Comment by Pizzalol** [comment]
All of those issues should be fixed and it should go through spell immunity properly now
