### ISSUE TITLE
Timberchain does nothing at all

### ISSUE THREAD

**Issue by AtroCty** [Pizzalol/SpellLibrary#101]
Title say everything.

Timberchain does nothing at all sadly.

**Comment by MNoya** [comment]
Timberchain is not scripted yet.

Refer to the [Progress spreadsheet](https://docs.google.com/spreadsheets/d/1oNoqMW2_PZ57TEonAQgMF-9JlApbt3LPNFtx72RhS8Y/edit#gid=0) (there's also a link in the readme)

**Comment by AtroCty** [comment]
https://www.reddit.com/r/Dota2Modding/comments/532vb7/timber_chain_particles_datadriven_timberchain/

I've recreated the chain, just need help with the particles. You can add it if you want to.
