### ISSUE TITLE
Bounty Hunter's Track particles

### ISSUE THREAD

**Issue by fcalife** [Pizzalol/SpellLibrary#11]
Track is missing its topmost particle: particles/units/heroes/hero_bounty_hunter/bounty_hunter_track_shield.vpcf

I tried adding it myself and it didn't show up, maybe attach_overhead doesn't work for it?

**Comment by MNoya** [comment]
Check Slardar Amplify damage, I think that particle child needs a lua SetParticleControlEnt for it to work

**Comment by fcalife** [comment]
From some more testing, seems like you just can't have "AttachEffect" and "EffectName" on the same modifier, with different particles. Attaching the shield particle in question to another modifier worked a-ok!

If no one's up to fix this one, I'll do it on the morn tomorrow

**Comment by Pizzalol** [comment]
A separate modifier is not needed, just add it in the OnCreated block + I fixed the missing smokey trail particle now :fire:
