### ISSUE TITLE
le bomberman fais [Trigger warning]

### ISSUE THREAD

**Issue by Attero** [Pizzalol/SpellLibrary#14]
le land main fais for le small globlin man doesnt blow up le ground kurukurukurus. also le flying fais are very [TRIGGERING]. very bad. fix pls.

**Comment by Attero** [comment]
dont just delete fix it you cuck.

**Comment by MNoya** [comment]
![img](http://static-cdn.jtvnw.net/emoticons/v1/360/1.0)
