### ISSUE TITLE
Dagon particle values is outside of range

### ISSUE THREAD

**Issue by vhpanisa** [Pizzalol/SpellLibrary#16]
https://github.com/Pizzalol/SpellLibrary/blob/SpellLibrary/game/dota_addons/spelllibrary/scripts/vscripts/items/item_dagon.lua#L8

Should have a " - 1"  after GetLevel() to conform into the right values of dagon particle

**Comment by MNoya** [comment]
Fixed thanks

**Comment by vhpanisa** [comment]
917d95 fixes
