### ISSUE TITLE
CreateTrackingProjectile usage

### ISSUE THREAD

**Issue by MNoya** [Pizzalol/SpellLibrary#2]
In the lua for Tinker Heat-Seeking Missiles I noticed this:

~~~
	local projTable = {
		EffectName = particle_name,
		Ability = ability,
		vSpawnOrigin = caster:GetAbsOrigin(),
		Target = v,
		Source = caster,
		bDodgeable = false,
		iMoveSpeed = 900,
		iUnitTargetTeam = DOTA_UNIT_TARGET_TEAM_ENEMY,
		iUnitTargetFlags = DOTA_UNIT_TARGET_FLAG_MAGIC_IMMUNE_ENEMIES,
		iUnitTargetType = DOTA_UNIT_TARGET_HERO
	}
	ProjectileManager:CreateTrackingProjectile( projTable )
~~~

This might be working correctly for this particular spell but I *think* the correct parameters for `CreateTrackingProjectile` are:

**Target** = target,
**Source** = caster,
**Ability** = ability,
**EffectName** = particle_name,
**bDodgeable** = false,
**bProvidesVision** = true,
**iMoveSpeed** = 900,
**iVisionRadius** = 0,
**iVisionTeamNumber** = caster:GetTeamNumber(),
**iSourceAttachment** = DOTA_PROJECTILE_ATTACHMENT_ATTACK_1

With these it should be the equal to the Datadriven version.

**Comment by kritth** [comment]
I've fixed the issue. The table should only include the correct values now. I will check again when I get home if it still works correctly.
