### ISSUE TITLE
possible reincarnatation fix

### ISSUE THREAD

**Issue by kallisti-dev** [Pizzalol/SpellLibrary#24]
So I was looking through the scripting API and noticed that the ForceKill function has a bReincarnate parameter. https://developer.valvesoftware.com/wiki/Dota_2_Workshop_Tools/Scripting/API/CDOTA_BaseNPC.ForceKill

Maybe using this instead of Kill would fix the problem with reincarnation adding to the death count?

**Comment by MNoya** [comment]
Unfortunately that parameter doesn't fix the problem (I believe I tested with every version of Kill types when I was coding this)
