### ISSUE TITLE
folder restructure

### ISSUE THREAD

**Issue by stephenfournier** [Pizzalol/SpellLibrary#31]
@Pizzalol do you mind if i restructure the folders? Ex. the abilities folder will contain subfolders for hero names. like: abilities > abaddon > aphotic_shield_datadriven.txt, borrowed_time_datadriven.txt, death_coil_datadriven.txt, frostmourne_datadriven.txt

ModKit now supports combine in sub-directories like this, and I'm currently developing a SpellLibrary browser inside ModKit. It has a few bugs currently mainly because I have to "guess" what the hero names are, and restructuring the folders this way would eliminate the need to guess.

http://gfycat.com/MisguidedFloweryAtlanticblackgoby

![](http://zippy.gfycat.com/MisguidedFloweryAtlanticblackgoby.gif)

**Comment by AVeryRandomPerson** [comment]
Would definitely make it more organised. and that looks like a pretty neat modkit function there :D

**Comment by stephenfournier** [comment]
nevermind, no need to do this anymore

**Comment by Pizzalol** [comment]
i actually didnt see this until now, does it still support subfolders?
