### ISSUE TITLE
item_tpscroll_datadriven is missing

### ISSUE THREAD

**Issue by Neojume** [Pizzalol/SpellLibrary#36]
I stumbled upon this library, which is awesome. But cannot find the tpscroll behavior?

**Comment by MNoya** [comment]
Not every ability or item is done yet

This is the item spreadsheet: https://docs.google.com/spreadsheets/d/1oNoqMW2_PZ57TEonAQgMF-9JlApbt3LPNFtx72RhS8Y/edit#gid=1940750752

 If you happen to need tpscroll and end up writing it, make a pull request with it to be added
