### ISSUE TITLE
Mana shield bugs

### ISSUE THREAD

**Issue by Tethrinaa** [Pizzalol/SpellLibrary#40]
Mana shield removes mana based on the post damage reduction, instead of based on the raw damage.

To properly deal damage the way dota (and wc3) did, you need to apply a damage reduction modifier for the absorption percent, then calculate back (using armor or magical armor as appropriate) and the absorption percent to get the original damage, then remove mana based on that original damage.

This has the side benefit of not needing the thinker to track hero health either, since the current health will always ALREADY be correct unless the user should run out of mana, in which case you damage the user as appropriate.

**Comment by RagnarHomsar** [comment]
Unfortunately, doing this in SpellLibrary is impossible, as far as I can tell. The only way to get the raw amount of damage dealt to a unit is a filter, which must be registered through the gametype object, which SpellLibrary doesn't have.

**Comment by RagnarHomsar** [comment]
This would be possible with a damage filter, but that has to be set on the global gametype, and I'm not entirely sure whether or not that'd be allowed to demonstrate just one ability.

**Comment by Tethrinaa** [comment]
Filter is not required (though that way would work too).  I did this for my ongoing Swat project in datadriven\lua.  It isn't on github yet, but should be tonight or this weekend, so you can take a look.

But here is the datadriven relevant portion, just add this to the existing mana shield data driven (without the comments, if you want):

			"modifier_mana_shield_datadriven"
			{
				"Properties"
				{
					// This property will reduce incoming damage by the % listed, making us not need to modify hero health later
					// and preventing heroes from dying when they shouldn't, requires calculating back out later in lua
					"MODIFIER_PROPERTY_INCOMING_DAMAGE_PERCENTAGE"	"%damage_reduction_percent"
				}

Where damage_reduction_percent is the negative of the mana shield absorption amount. (so a -60 means take 60% reduced damage)

This causes the hero to never take the damage in the first place.  THEN, in the LUA I added the following:

	local armor = caster:GetPhysicalArmorValue()
	local armor_percent = 1 - (100 / (100 + 6 * armor))

	-- This ones tricky
	-- First term:  (damage / damage_per_mana) converts damage dealt to mana
	-- Second term: (1 / (1 - absorption_percent/100)) undoes the damage reduction given by the modifier in the datadriven, this prevents the hero from being DEAD before we 'undo' the damage
	-- Third term: (1 / (1 - armor_percent/100)) undoes the damage reduction from armor, since we remove mana first
	local mana_needed = (damage / damage_per_mana) * (1 / (1 - absorption_percent)) * (1 / (1 - armor_percent)) * absorption_percent

So the basic logical flow for a 50% mana shield with 2 damage per mana (and 50% armor for easy numbers) would be the following:

Hero gets hit by 100 damage.  50 damage is blocked by the modifier that reduces damage taken, and 25 damage is blocked by armor, so by the time we call ManaShield, the damage passed in is 25.  Fetching the reduction gives us 50% for both armor and the modifier so we get:
	(25/2) * (1/(1-0.50)) * (1 / (1 - 0.50)) * 0.50
	12.5 * 2 * 2 * 0.5
	25
So the hero would lose 25 mana, which is correct, since 100 damage on a 50% shield should cause the hero to take 50 damage to the shield, at 2 damage per mana, that is 25 mana.

There is one other check you need, to handle the case where the user does not have as much mana as you want to remove.  Here's how I wrote it:

		-- If the caster has enough mana, remove the necessary mana
		if mana_needed <= caster_mana then
			caster:SpendMana(mana_needed, ability)

			-- No longer need to change health, since the modifier with damage reduction makes health already correct
			-- caster:SetHealth(oldHealth)
			
			-- Impact particle based on damage absorbed
			local particleName = "particles/units/heroes/hero_medusa/medusa_mana_shield_impact.vpcf"
			local particle = ParticleManager:CreateParticle(particleName, PATTACH_ABSORIGIN_FOLLOW, caster)
			ParticleManager:SetParticleControl(particle, 0, caster:GetAbsOrigin())
			ParticleManager:SetParticleControl(particle, 1, Vector(mana_needed,0,0))
		else
			-- User doesn't have enough mana, remove all of their mana and damage them appropriately
			caster:SpendMana(caster_mana, ability)
			local hp_to_remove = (mana_needed - caster_mana) * damage_per_mana * armor_percent
			if hp_to_remove < health then
				local newHealth = health - hp_to_remove
				caster:SetHealth(newHealth)
			else
				caster:ForceKill(false)
			end
		end

I have not tested this last part, but the first part works exactly correct in my testing.  The great part imo is that it gets rid of the thinker, which can cause you to lose up to 0.03 seconds of health regen.  Not a huge deal, but always nice to get it *more* correct.

Happy to help!

Teth

**Comment by Tethrinaa** [comment]
My full ManaShield function, in case I missed anything above:

function ManaShield( event )
	local caster = event.caster
	local ability = event.ability
	local damage_per_mana = 1 / ability:GetLevelSpecialValueFor("efficiency", ability:GetLevel() - 1 )
	local absorption_percent = ability:GetLevelSpecialValueFor("absorption_tooltip", ability:GetLevel() - 1 ) * 0.01
	local damage = event.Damage
	local health = caster:GetHealth()
	local armor = caster:GetPhysicalArmorValue()
	local armor_percent = 1 - (100 / (100 + 6 * armor))
	local caster_mana = caster:GetMana()
	-- This ones tricky
	-- First term:  (damage / damage_per_mana) converts damage dealt to mana
	-- Second term: (1 / (1 - absorption_percent/100)) undoes the damage reduction given by the modifier in the datadriven, this prevents the hero from being DEAD before we 'undo' the damage
	-- Third term: (1 / (1 - armor_percent/100)) undoes the damage reduction from armor, since we remove mana first
	local mana_needed = (damage / damage_per_mana) * (1 / (1 - absorption_percent)) * (1 / (1 - armor_percent)) * absorption_percent

	-- We're ignoring armor absorption, need to do that later

	-- If it doesnt then do the HP calculation
	if health >= 1 then
		print("Damage taken "..damage.." | Mana needed: "..mana_needed.." | Current Mana: "..caster_mana.." | absorption %" ..absorption_percent.." | armor_percent "..armor_percent)

		-- If the caster has enough mana, remove the necessary mana
		if mana_needed <= caster_mana then
			caster:SpendMana(mana_needed, ability)

			-- No longer need to change health, since the modifier with damage reduction makes health already correct
			-- caster:SetHealth(oldHealth)
			
			-- Impact particle based on damage absorbed
			local particleName = "particles/units/heroes/hero_medusa/medusa_mana_shield_impact.vpcf"
			local particle = ParticleManager:CreateParticle(particleName, PATTACH_ABSORIGIN_FOLLOW, caster)
			ParticleManager:SetParticleControl(particle, 0, caster:GetAbsOrigin())
			ParticleManager:SetParticleControl(particle, 1, Vector(mana_needed,0,0))
		else
			-- User doesn't have enough mana, remove all of their mana and damage them appropriately
			caster:SpendMana(caster_mana, ability)
			local hp_to_remove = (mana_needed - caster_mana) * damage_per_mana * armor_percent
			if hp_to_remove < health then
				local newHealth = health - hp_to_remove
				caster:SetHealth(newHealth)
			else
				caster:ForceKill(false)
			end
		end
	end	
end

NOTE that I switched damage_per_mana's declare to be 1/ the datadriven.  I did this because the SWAT wiki records things in "efficiency", so you should switch that variable back, but the rest of it should be correct for dota2.

**Comment by Tethrinaa** [comment]
This also only works for phys damage, I'll need to fix that in my version too.

**Comment by MNoya** [comment]
Yeah using `MODIFIER_PROPERTY_INCOMING_DAMAGE_PERCENTAGE` and just backtracking the mana needed for each damage taken sounds like it'd work.

**Comment by Pizzalol** [comment]
Isn't the damage type access still Lua only? Gonna leave it as it is unless someone wants to rewrite it as a Lua ability
