### ISSUE TITLE
OD AI missing banishment component

### ISSUE THREAD

**Issue by MNoya** [Pizzalol/SpellLibrary#5]
[Astral Imprisonment](https://github.com/Pizzalol/SpellLibrary/blob/SpellLibrary/game/dota_addons/spelllibrary/scripts/npc/abilities/obsidian_destroyer_astral_imprisonment_datadriven.txt) doesn't hide the hero while out of game.

Don't mark this as *Finished*, specially without leaving a note for missing things as obvious as this one.

**Comment by ynohtna92** [comment]
The current way the hide hero is coded does not accurately hide all particles on the hero or the hull. 

Use NoDraw instead:

    event.caster:AddNoDraw()
    event.caster:RemoveNoDraw()

**Comment by MNoya** [comment]
AFAIK AddNoDraw still shows the hero particles? Or maybe it's just the cosmetics, I tried abaddon and the horse glow would still be shown with NoDraw

**Comment by ynohtna92** [comment]
Any particles tied to the hero cosmetics disappear. I just tried abaddon and the horse glow wasn't there.

**Comment by MNoya** [comment]
Alright, good to know, we'll fix it in this and other abilities that were using the HideWearables, thanks! :)
