### ISSUE TITLE
Chaos Knight Phantasm duplicate items

### ISSUE THREAD

**Issue by RodneyMcKay** [Pizzalol/SpellLibrary#57]
I'm using the ability for my mod, haven't modified any code in it, it's in juggernaut. First it seems to store items when cast the first time, and then when casted again it keeps the stored items from the first time casted, and duplicates other new items in base.

**Comment by Pizzalol** [comment]
I am unable to reproduce the bug and I can't find any reference to the code in your X Hero Siege repository(assuming thats the mod you were referring to).

Upload the code and maybe I can help you figure out what the problem is

**Comment by RodneyMcKay** [comment]
http://hastebin.com/ivoyozukaw.js

**Comment by Pizzalol** [comment]
The code looks alright so I'm not sure what the problem could be

**Comment by RodneyMcKay** [comment]
looks like for some reason it keeps items, maybe i can try make a remove items before add again..
