### ISSUE TITLE
Desolator Datadriven Bug

### ISSUE THREAD

**Issue by RodneyMcKay** [Pizzalol/SpellLibrary#59]
I'm using it in X Hero Siege( again ) and the first shot applies armor reduction after the damage, wich makes the difference not a big deal, but with a modified deso that reduce armor from -100 per example you feel it when the first shot deals like 50 dmg, and the 2nd 700.

**Comment by MNoya** [comment]
Just change OnAttackLanded to OnAttack

**Comment by RodneyMcKay** [comment]
Will it apply if the Attack is missed?

**Comment by vVv-AA** [comment]
Misses are not supposed to apply Desolate if it works as in Dota.

**Comment by RodneyMcKay** [comment]
Okay i thought it was needed to mention in code to not apply if missed, thanks for the help works fine, i think you guys should make the change too in the spell Library too!

**Comment by fcalife** [comment]
Is your desolator supposed to do anything beyond the regular one's effects?
Wouldn't it be easier to edit it instead?

2015-12-14 15:26 GMT-03:00 Cookies <notifications@github.com>:

> Okay i thought it was needed to mention in code to not apply if missed,
> thanks for the help works fine, i think you guys should make the change too
> in the spell Library too!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Pizzalol/SpellLibrary/issues/59#issuecomment-164517805>
> .
>



-- 
Felipe Calife

**Comment by RodneyMcKay** [comment]
Yes it should, and with noya's fix it does, but what i'm trying to say is that the datadriven desolator should apply damage before impact, as the regular does in dota 2
