### ISSUE TITLE
Date format convention 

### ISSUE THREAD

**Issue by MNoya** [Pizzalol/SpellLibrary#84]
The current Day.Month.Year `12.02.2016` can be confused with the american date system (meaning 12 of February or December 2nd), let's try to do "February 12, 2016" as the date format.

**Comment by Pizzalol** [comment]
What about Year.Month.Day? Some people might have issues with the month names

**Comment by YOLOSPAGHETTI** [comment]
I've been doing the "February 12, 2016" format just because I am also used to the american date system, and I don't really see how it could be confusing.

**Comment by Pizzalol** [comment]
Alright, will switch over to the new format then

**Comment by MNoya** [comment]
It's not really important to go back and edit it, just a thing to keep in mind and [updating the readme](https://github.com/Pizzalol/SpellLibrary/blob/master/README.md)

**Comment by Pizzalol** [comment]
Updating the readme is on my TODO list, will see if i can do at least a part in the next 2 days
