### ISSUE TITLE
Windrunner's Powershot

### ISSUE THREAD

**Issue by DieCriminal** [Pizzalol/SpellLibrary#86]
Powershot bugs if a unit it hits is close to you.(Melee/Close range, don't have exact range.)

**It gives this error:**
 [ W VScript ]: Script Runtime Error: ...es\scripts\vscripts\heroes\hero_windrunner\powershot.lua:109: attempt to index field 'powershot_units_array' (a nil value)
[ W VScript ]: stack traceback:
[ W VScript ]: 	...es\scripts\vscripts\heroes\hero_windrunner\powershot.lua:109: in function <...es\scripts\vscripts\heroes\hero_windrunner\powershot.lua:71>

And then it doesn't apply damage anything that gets hit. Even the units that are not close to you.
If it doesn't hit a unit that is close to you it will work as intended.

**How to reproduce:**
Create a kobold in melee range and a kobold far way behind the first one.Fire you powershot and note that no kobold gets damaged.

If instead you put both far from you and powershot them  it works as intended.

**Comment by YOLOSPAGHETTI** [comment]
Should work now.
