### ISSUE TITLE
Skeleton Vampiric Script path not correct

### ISSUE THREAD

**Issue by zombieJ** [Pizzalol/SpellLibrary#87]
Hi, I found your script path 'king' missing 'ing':
https://github.com/Pizzalol/SpellLibrary/blob/master/game/scripts/npc/abilities/skeleton_king_vampiric_aura_datadriven.txt#L54

```
"ScriptFile"	"heroes/hero_skeleton_k/vampiric_aura.lua"
```

which should be

```
"ScriptFile"	"heroes/hero_skeleton_king/vampiric_aura.lua"
```

Thanks~

**Comment by YOLOSPAGHETTI** [comment]
Good catch!
