### ISSUE TITLE
Wraith King's Hellfire Blast doesn't have the "warmup" particle effect that it normally has on his arm

### ISSUE THREAD

**Issue by Davoness** [Pizzalol/SpellLibrary#9]

**Comment by Pizzalol** [comment]
I will look into it today once I return from uni

**Comment by MNoya** [comment]
Well, these are hero-related attachment which we can't ensure they will be present on any hero, but still worth putting them in I guess

**Comment by Pizzalol** [comment]
It is a weird particle, but as long as the hero has an attack attachment then it should work otherwise its just hidden under the map and it didnt take long to fix so its a win-win :+1:
